version: '3'

volumes:
  sqlite3:

services:
  backend:
    image: anstane/django_stripe_app
    env_file: .env
    command: >
      sh -c "poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py migrate --run-syncdb &&
             poetry run python manage.py createsuperuser --noinput &&
             poetry run python manage.py create_items &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - sqlite3:/data/
