# Generated by Django 5.0.1 on 2024-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_stripe_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
